name: Python tests and flake8

on:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Install dependencies
        run: |
          conda create --yes --name unittest python=3.10
          cd ..
          git clone https://github.com/SchindlerReGIS/rws2.git
          cd rws2
          pip install -e .
      - name: Install
        run: |
          pip install -e .
      - name: Lint with flake8
        run: |
          conda install flake8
          flake8 .
      - name: Unittests
        run: |
          python -m unittest discover tests
